[build-system]
requires = [
    "setuptools >= 66",
    "setuptools_scm[toml]>=6.2",
    "wheel >= 0.38.4",
]
build-backend = 'setuptools.build_meta'

[tool.setuptools_scm]
fallback_version = "unknown"
local_scheme = "node-and-date"
write_to = "src/ssec_project/version.py"
